# Generated by Django 5.0.3 on 2024-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0002_signin_signup_voterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
